// flow-typed signature: 3ccab43c70d04cf3bd042430f3ef2370
// flow-typed version: <<STUB>>/@team-griffin/install-self-peers_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@team-griffin/install-self-peers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@team-griffin/install-self-peers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@team-griffin/install-self-peers/lib/cli' {
  declare module.exports: any;
}

declare module '@team-griffin/install-self-peers/lib/index' {
  declare module.exports: any;
}

declare module '@team-griffin/install-self-peers/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@team-griffin/install-self-peers/lib/cli.js' {
  declare module.exports: $Exports<'@team-griffin/install-self-peers/lib/cli'>;
}
declare module '@team-griffin/install-self-peers/lib/index.js' {
  declare module.exports: $Exports<'@team-griffin/install-self-peers/lib/index'>;
}
declare module '@team-griffin/install-self-peers/lib/utils.js' {
  declare module.exports: $Exports<'@team-griffin/install-self-peers/lib/utils'>;
}
